"""create users table

Revision ID: 030e014ba3e0
Revises: bf3f1527b6d1
Create Date: 2023-12-06 06:52:25.020699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030e014ba3e0'
down_revision = 'bf3f1527b6d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
