"""creat users table

Revision ID: 191e6ef208b1
Revises: fa17ebbe2192
Create Date: 2023-11-28 22:58:48.246500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191e6ef208b1'
down_revision = 'fa17ebbe2192'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
