"""update doctor table-day

Revision ID: 400b78fadc2c
Revises: 6a848480336c
Create Date: 2023-12-07 23:03:24.450407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400b78fadc2c'
down_revision = '6a848480336c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('day', sa.String(), nullable=False))
    op.drop_column('doctors', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('doctors', 'day')
    # ### end Alembic commands ###
