"""update doctor table

Revision ID: 6a848480336c
Revises: 3188c0323ee4
Create Date: 2023-12-07 22:59:35.874802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a848480336c'
down_revision = '3188c0323ee4'
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add the `day` column with a default value
    op.add_column('doctors', sa.Column('day', sa.String(), nullable=False, server_default='default_day'))

    # Step 2: Alter the `day` column to remove the default value
    op.alter_column('doctors', 'day', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='unique')
    op.create_unique_constraint('doctors_price_key', 'doctors', ['price'])
    # ### end Alembic commands ###
