"""update doctor table-day

Revision ID: aa5cb96b67ce
Revises: 0a70cc3cba48
Create Date: 2023-12-07 23:09:35.432045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5cb96b67ce'
down_revision = '0a70cc3cba48'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('day', sa.String(), nullable=True))
    op.drop_column('doctors', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('doctors', 'day')
    # ### end Alembic commands ###
