"""create users table

Revision ID: bf3f1527b6d1
Revises: d4b392539c2c
Create Date: 2023-12-06 06:51:50.522195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3f1527b6d1'
down_revision = 'd4b392539c2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
